version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker build -t $REPOSITORY_URI:backend ./backend
      - docker build -t $REPOSITORY_URI:frontend ./frontend
      - docker tag $REPOSITORY_URI:backend $REPOSITORY_URI:backend-latest
      - docker tag $REPOSITORY_URI:frontend $REPOSITORY_URI:frontend-latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:backend
      - docker push $REPOSITORY_URI:frontend
      - docker push $REPOSITORY_URI:backend-latest
      - docker push $REPOSITORY_URI:frontend-latest
      - echo Writing image definitions file...
      - printf '[{"name":"backend","imageUri":"%s"}]' $REPOSITORY_URI:backend-latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
