export const KOKORO_VOICES = [
  { id: 'af_heart', name: 'Heart (Female)' },
  { id: 'af_alloy', name: 'Alloy (Female)' },
  { id: 'af_aoede', name: 'Aoede (Female)' },
  { id: 'af_bella', name: 'Bella (Female)' },
  { id: 'af_jessica', name: 'Jessica (Female)' },
  { id: 'af_kore', name: 'Kore (Female)' },
  { id: 'af_nicole', name: 'Nicole (Female)' },
  { id: 'af_nova', name: 'Nova (Female)' },
  { id: 'af_river', name: 'River (Female)' },
  { id: 'af_sarah', name: 'Sarah (Female)' },
  { id: 'af_sky', name: 'Sky (Female)' },
  { id: 'am_adam', name: 'Adam (Male)' },
  { id: 'am_echo', name: 'Echo (Male)' },
  { id: 'am_eric', name: 'Eric (Male)' },
  { id: 'am_fenrir', name: 'Fenrir (Male)' },
  { id: 'am_liam', name: 'Liam (Male)' },
  { id: 'am_michael', name: 'Michael (Male)' },
  { id: 'am_onyx', name: 'Onyx (Male)' },
  { id: 'am_puck', name: 'Puck (Male)' },
  { id: 'am_santa', name: 'Santa (Male)' },
];
