import React from 'react';
import { motion } from 'framer-motion';
import { useArticles } from '../hooks/useArticles';
import { ArticleCard } from '../components/home/ArticleCard';

const Home: React.FC = () => {
  const { articles, loading } = useArticles();

  if (loading) return (
    <div className="flex justify-center items-center h-64">
      <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gray-900"></div>
    </div>
  );

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0 }}
      className="space-y-8"
    >
      <div className="text-center space-y-4 mb-12">
        <h1 className="text-5xl font-bold tracking-tight text-gray-900">Latest Insights</h1>
        <p className="text-xl text-gray-500 max-w-2xl mx-auto">
          Explore thoughts and stories generated by our local AI models.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {articles.map((article, index) => (
          <ArticleCard key={article.id} article={article} index={index} />
        ))}
      </div>
    </motion.div>
  );
};

export default Home;
